route:
  group_by: ['alertname', 'job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'slack-notifications'

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - api_url_file: '/etc/alertmanager/slack_webhook.txt'
        channel: '#shashti-karz-status'

  - name: 'email-notifications'
    # email_configs:
    #   - to: 'your-email@example.com'
    #     from: 'grafana@shashtikarz.app'
    #     smarthost: 'smtp.gmail.com:587'
    #     auth_username: 'your-email@example.com'
    #     auth_identity: 'your-email@example.com'
    #     auth_password: 'your-app-password'
    #     send_resolved: true
