services:
  # Prometheus
  - type: web
    name: shashti-prometheus
    env: docker
    dockerContext: .
    dockerfilePath: deployment/prometheus.Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 9090

  # Grafana
  - type: web
    name: shashti-grafana
    env: docker
    dockerContext: .
    dockerfilePath: deployment/grafana.Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 3000

  # Alertmanager
  - type: pserv
    name: shashti-alertmanager
    env: docker
    dockerContext: .
    dockerfilePath: deployment/alertmanager.Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 9093
